//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicRemoteService.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MagicRemoteService.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {
        ///	&quot;id&quot;: &quot;com.cathwyler.magicremoteservice&quot;,
        ///	&quot;title&quot;: &quot;MagicRemoteService&quot;,
        ///	&quot;main&quot;: &quot;index.html&quot;,
        ///	&quot;icon&quot;: &quot;icon.png&quot;,
        ///	&quot;largeIcon&quot;: &quot;largeIcon.png&quot;,
        ///	&quot;iconColor&quot;: &quot;#575E66&quot;,
        ///	&quot;type&quot;: &quot;web&quot;,
        ///	&quot;vendor&quot;: &quot;Cathwyler&quot;,
        ///	&quot;version&quot;: &quot;1.0.0&quot;,
        ///	&quot;appDescription&quot;: &quot;Service providing computer remote control using a LG WebOS TV&quot;,
        ///	&quot;bgColor&quot;: &quot;#575E66&quot;,
        ///	&quot;supportTouchMode&quot;: &quot;none&quot;,
        ///	&quot;disableBackHistoryAPI&quot;: true,
        ///	&quot;transparent&quot;: true,
        ///	&quot;supportGIP&quot;: true
        ///}.
        /// </summary>
        internal static string appinfo {
            get {
                return ResourceManager.GetString("appinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exit.
        /// </summary>
        internal static string ApplicationExit {
            get {
                return ResourceManager.GetString("ApplicationExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        internal static string ApplicationSetting {
            get {
                return ResourceManager.GetString("ApplicationSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Keyboard.
        /// </summary>
        internal static string BindActionValueKeyboard {
            get {
                return ResourceManager.GetString("BindActionValueKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Shutdown.
        /// </summary>
        internal static string BindActionValueShutdown {
            get {
                return ResourceManager.GetString("BindActionValueShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        internal static string BindKeyboardErreur {
            get {
                return ResourceManager.GetString("BindKeyboardErreur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Left button.
        /// </summary>
        internal static string BindMouseValueLeft {
            get {
                return ResourceManager.GetString("BindMouseValueLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Middle button.
        /// </summary>
        internal static string BindMouseValueMiddle {
            get {
                return ResourceManager.GetString("BindMouseValueMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Right button.
        /// </summary>
        internal static string BindMouseValueRight {
            get {
                return ResourceManager.GetString("BindMouseValueRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {
        ///	&quot;id&quot;: &quot;com.cathwyler.magicremoteservice&quot;,
        ///	&quot;title&quot;: &quot;MagicRemoteService&quot;,
        ///	&quot;appDescription&quot;: &quot;Service permettant de contrôler un ordinateur à l&apos;aide d&apos;une TV WebOS LG&quot;,
        ///	&quot;version&quot;: &quot;1.0.0&quot;
        ///}.
        /// </summary>
        internal static string frappinfo {
            get {
                return ResourceManager.GetString("frappinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///
        ///&lt;head&gt;
        ///	&lt;title&gt;MagicRemoteService&lt;/title&gt;
        ///	&lt;style type=&quot;text/css&quot;&gt;
        ///		@font-face {
        ///			font-family: Sandstone;
        ///			src: url(&quot;MuseoSans-Medium.ttf&quot;);
        ///		}
        ///		* {
        ///			font-family: Sandstone;
        ///			text-overflow: ellipsis;
        ///		}
        ///
        ///		body {
        ///			margin:0;
        ///			padding:0;
        ///		}
        ///
        ///		.screen {
        ///			position: fixed;
        ///			pointer-events: none;
        ///			
        ///			height: 100%;
        ///			width: 100%;
        ///		}
        ///
        ///		div.flex {
        ///			display: flex;
        ///			flex-flow: row wrap;
        ///			/*gap: 1rem; chrome &lt; 84*/
        ///		}
        ///		div.just [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string index {
            get {
                return ResourceManager.GetString("index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} is not a valid entry. Please specify a value between 1 and 255..
        /// </summary>
        internal static string IPAddressBoxErrorByteEntryMessage {
            get {
                return ResourceManager.GetString("IPAddressBoxErrorByteEntryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid entry.
        /// </summary>
        internal static string IPAddressBoxErrorByteEntryTitle {
            get {
                return ResourceManager.GetString("IPAddressBoxErrorByteEntryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You are trying to copy an incorrectly formatted IP address into this field..
        /// </summary>
        internal static string IPAddressBoxErrorPasteMessage {
            get {
                return ResourceManager.GetString("IPAddressBoxErrorPasteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Badly formatted IP address.
        /// </summary>
        internal static string IPAddressBoxErrorPasteTitle {
            get {
                return ResourceManager.GetString("IPAddressBoxErrorPasteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] largeIcon {
            get {
                object obj = ResourceManager.GetObject("largeIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        /// </summary>
        internal static System.Drawing.Icon MagicRemoteService {
            get {
                object obj = ResourceManager.GetObject("MagicRemoteService", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 
        ///ArrayBuffer.prototype.toString = function(base) {
        ///	return [].slice.call(new Uint8Array(this)).map(function(x) {
        ///		return (&quot;00&quot; + x.toString(base)).slice(-2);
        ///	}).join(&quot;&quot;);
        ///}
        ///
        ///function Toast(sTitre, sMessage){
        ///	CancelToast();
        ///	var deScreen = document.createElement(&quot;div&quot;);
        ///	deScreen.className = &quot;screen flex justify-center align-flex-end&quot;;
        ///	var deLog = document.createElement(&quot;div&quot;);
        ///	deLog.className = &quot;window&quot;;
        ///	deLog.id = &quot;toast&quot;
        ///	deLog.addEventListener(&quot;click&quot;, CancelToast);
        ///	var dePopupTitre [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string main {
            get {
                return ResourceManager.GetString("main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] MuseoSans_Medium {
            get {
                object obj = ResourceManager.GetObject("MuseoSans_Medium", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {
        ///    &quot;name&quot;: &quot;com.cathwyler.magicremoteservice.send&quot;,
        ///    &quot;version&quot;: &quot;1.0.0&quot;,
        ///    &quot;description&quot;: &quot;Send service&quot;,
        ///    &quot;main&quot;: &quot;send.js&quot;,
        ///    &quot;scripts&quot;: {
        ///        &quot;test&quot;: &quot;echo \&quot;Error: no test specified\&quot; &amp;&amp; exit 1&quot;
        ///    },
        ///    &quot;author&quot;: &quot;&quot;,
        ///    &quot;license&quot;: &quot;BSD&quot;
        ///}.
        /// </summary>
        internal static string package {
            get {
                return ResourceManager.GetString("package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} is not a valid entry. Please specify a value between 0x00 and 0xFF..
        /// </summary>
        internal static string PhysicalAddressBoxErrorByteEntryMessage {
            get {
                return ResourceManager.GetString("PhysicalAddressBoxErrorByteEntryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid entry.
        /// </summary>
        internal static string PhysicalAddressBoxErrorByteEntryTitle {
            get {
                return ResourceManager.GetString("PhysicalAddressBoxErrorByteEntryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You are trying to copy an incorrectly formatted physical address into this field..
        /// </summary>
        internal static string PhysicalAddressBoxErrorPasteMessage {
            get {
                return ResourceManager.GetString("PhysicalAddressBoxErrorPasteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Badly formatted physical address.
        /// </summary>
        internal static string PhysicalAddressBoxErrorPasteTitle {
            get {
                return ResourceManager.GetString("PhysicalAddressBoxErrorPasteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 
        ///const oStringDefault = {
        ///	strAppTittle: &quot;MagicRemoteService&quot;,
        ///	strAppDescription: &quot;Service providing computer remote control using a LG WebOS TV&quot;,
        ///
        ///	strLogTitle: &quot;Log&quot;,
        ///	strWarnTitle: &quot;Warn&quot;,
        ///	strErrorTitle: &quot;Error&quot;,
        ///
        ///	strLaunchAppSuccess: &quot;Success to launch {1}&quot;,
        ///	strLaunchAppFailure: &quot;Failed to launch {1}&quot;,
        ///	strGetAllInputStatusSubscribe: &quot;Start to get all input status&quot;,
        ///	strGetAllInputStatusFailure: &quot;Failed to get all input status&quot;,
        ///	strSendWolSuccess: &quot;Success to send WoL&quot;,
        ///	strSendWolFai [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string ressource {
            get {
                return ResourceManager.GetString("ressource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 
        ///var pkgInfo = require(&quot;./package.json&quot;);
        ///var Service = require(&quot;webos-service&quot;);
        ///var Dgram = require(&quot;dgram&quot;);
        ///
        ///var serService = new Service(pkgInfo.name);
        ///
        ///var socClient = Dgram.createSocket(&quot;udp4&quot;);
        ///socClient.bind(function() {
        ///	socClient.setBroadcast(true);
        ///});
        ///
        ///var bufWol = Buffer.alloc(102);
        ///bufWol.fill(0xFF, 0, 6);
        ///
        ///serService.register(&quot;wol&quot;, function(mMessage) {
        ///	try {
        ///		bufWol.fill(Buffer.from(mMessage.payload.mMac.tabMac), 6);
        ///		socClient.send(bufWol, 9, mMessage.payload.sBroadcas [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {
        ///    &quot;id&quot;: &quot;com.cathwyler.magicremoteservice.send&quot;,
        ///    &quot;description&quot;: &quot;Send Service&quot;,
        ///    &quot;services&quot;: [
        ///        {
        ///            &quot;name&quot;: &quot;com.cathwyler.magicremoteservice.send&quot;
        ///        }
        ///    ]
        ///}.
        /// </summary>
        internal static string services {
            get {
                return ResourceManager.GetString("services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error refreshing TV inputs.
        /// </summary>
        internal static string SettingInputRefreshlErrorTitle {
            get {
                return ResourceManager.GetString("SettingInputRefreshlErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please select a TV input..
        /// </summary>
        internal static string SettingInputSelectErrorMessage {
            get {
                return ResourceManager.GetString("SettingInputSelectErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The TV input has not been selected.
        /// </summary>
        internal static string SettingInputSelectErrorTitle {
            get {
                return ResourceManager.GetString("SettingInputSelectErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} is not a valid physical address. Please specify a valid physical address..
        /// </summary>
        internal static string SettingPCMacErrorMessage {
            get {
                return ResourceManager.GetString("SettingPCMacErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid physical address.
        /// </summary>
        internal static string SettingPCMacErrorTitle {
            get {
                return ResourceManager.GetString("SettingPCMacErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while saving PC configuration.
        /// </summary>
        internal static string SettingPCSaveErrorTittle {
            get {
                return ResourceManager.GetString("SettingPCSaveErrorTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to save the changes made to the PC service ?.
        /// </summary>
        internal static string SettingPCSaveMessage {
            get {
                return ResourceManager.GetString("SettingPCSaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while saving remote configuration.
        /// </summary>
        internal static string SettingRemoteSaveErrorTittle {
            get {
                return ResourceManager.GetString("SettingRemoteSaveErrorTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to save the changes made to the remote keybind ?.
        /// </summary>
        internal static string SettingRemoteSaveMessage {
            get {
                return ResourceManager.GetString("SettingRemoteSaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} is not a valid IP address. Please specify a valid IP address..
        /// </summary>
        internal static string SettingSendIPErrorMessage {
            get {
                return ResourceManager.GetString("SettingSendIPErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid IP address.
        /// </summary>
        internal static string SettingSendIPErrorTitle {
            get {
                return ResourceManager.GetString("SettingSendIPErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} is not a valid subnet mask. Please specify a valid subnet mask..
        /// </summary>
        internal static string SettingSubnetMaskErrorMessage {
            get {
                return ResourceManager.GetString("SettingSubnetMaskErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid subnet mask.
        /// </summary>
        internal static string SettingSubnetMaskErrorTitle {
            get {
                return ResourceManager.GetString("SettingSubnetMaskErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while adding TV.
        /// </summary>
        internal static string SettingTVAddErrorTitle {
            get {
                return ResourceManager.GetString("SettingTVAddErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while installing app on TV.
        /// </summary>
        internal static string SettingTVInstallErrorTitle {
            get {
                return ResourceManager.GetString("SettingTVInstallErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while modifying TV.
        /// </summary>
        internal static string SettingTVModifyErrorTitle {
            get {
                return ResourceManager.GetString("SettingTVModifyErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while refreshing TVs.
        /// </summary>
        internal static string SettingTVRefreshlErrorTitle {
            get {
                return ResourceManager.GetString("SettingTVRefreshlErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while removing TV.
        /// </summary>
        internal static string SettingTVRemoveErrorTitle {
            get {
                return ResourceManager.GetString("SettingTVRemoveErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to install the changes made to the TV app ?.
        /// </summary>
        internal static string SettingTVSaveMessage {
            get {
                return ResourceManager.GetString("SettingTVSaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please select a TV.
        /// </summary>
        internal static string SettingTVSelectErrorMessage {
            get {
                return ResourceManager.GetString("SettingTVSelectErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The TV has not been selected.
        /// </summary>
        internal static string SettingTVSelectErrorTitle {
            get {
                return ResourceManager.GetString("SettingTVSelectErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à WebOS TV CLI must be installed..
        /// </summary>
        internal static string WebOSCLINotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("WebOSCLINotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à window.webOS=function(e){var n={};function r(t){if(n[t])return n[t].exports;var o=n[t]={i:t,l:!1,exports:{}};return e[t].call(o.exports,o,o.exports,r),o.l=!0,o.exports}return r.m=e,r.c=n,r.d=function(e,n,t){r.o(e,n)||Object.defineProperty(e,n,{enumerable:!0,get:t})},r.r=function(e){&quot;undefined&quot;!=typeof Symbol&amp;&amp;Symbol.toStringTag&amp;&amp;Object.defineProperty(e,Symbol.toStringTag,{value:&quot;Module&quot;}),Object.defineProperty(e,&quot;__esModule&quot;,{value:!0})},r.t=function(e,n){if(1&amp;n&amp;&amp;(e=r(e)),8&amp;n)return e;if(4&amp;n&amp;&amp;&quot;object&quot;==type [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string webOSTV {
            get {
                return ResourceManager.GetString("webOSTV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à window.webOSDev=function(e){var r={};function t(n){if(r[n])return r[n].exports;var i=r[n]={i:n,l:!1,exports:{}};return e[n].call(i.exports,i,i.exports,t),i.l=!0,i.exports}return t.m=e,t.c=r,t.d=function(e,r,n){t.o(e,r)||Object.defineProperty(e,r,{enumerable:!0,get:n})},t.r=function(e){&quot;undefined&quot;!=typeof Symbol&amp;&amp;Symbol.toStringTag&amp;&amp;Object.defineProperty(e,Symbol.toStringTag,{value:&quot;Module&quot;}),Object.defineProperty(e,&quot;__esModule&quot;,{value:!0})},t.t=function(e,r){if(1&amp;r&amp;&amp;(e=t(e)),8&amp;r)return e;if(4&amp;r&amp;&amp;&quot;object&quot;==t [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string webOSTV_dev {
            get {
                return ResourceManager.GetString("webOSTV_dev", resourceCulture);
            }
        }
    }
}
