//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicRemoteService.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MagicRemoteService.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {
        ///	&quot;id&quot;: &quot;com.cathwyler.magicremoteservice&quot;,
        ///	&quot;main&quot;: &quot;index.html&quot;,
        ///	&quot;title&quot;: &quot;MagicRemoteService&quot;,
        ///	&quot;icon&quot;: &quot;icon.png&quot;,
        ///	&quot;miniIcon&quot;: &quot;miniIcon.png&quot;,
        ///	&quot;largeIcon&quot;: &quot;largeIcon.png&quot;,
        ///	&quot;type&quot;: &quot;web&quot;,
        ///	&quot;vendor&quot;: &quot;Cathwyler&quot;,
        ///	&quot;version&quot;: &quot;1.0.0&quot;,
        ///	&quot;bgColor&quot;: &quot;#575E66&quot;,
        ///	&quot;iconColor&quot;: &quot;#575E66&quot;,
        ///	&quot;appDescription&quot;: &quot;HDMI&quot;,
        ///	&quot;appDescriptionLong&quot;: &quot;Service providing computer remote control using a LG WebOS TV&quot;,
        ///	&quot;disableBackHistoryAPI&quot;: true,
        ///	&quot;transparent&quot;: true,
        ///	&quot;defaultWindowType&quot;: &quot;floating&quot;,
        ///	&quot; [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string appinfo {
            get {
                return ResourceManager.GetString("appinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exit.
        /// </summary>
        internal static string ApplicationExit {
            get {
                return ResourceManager.GetString("ApplicationExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        internal static string ApplicationSetting {
            get {
                return ResourceManager.GetString("ApplicationSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {
        ///	&quot;strAppTittle&quot;: &quot;MagicRemoteService&quot;,
        ///	&quot;strAppDescription&quot;: &quot;HDMI&quot;,
        ///	&quot;strAppDescriptionLong&quot;: &quot;Service providing computer remote control using a LG WebOS TV&quot;,
        ///
        ///	&quot;strLogTitle&quot;: &quot;Log&quot;,
        ///	&quot;strWarnTitle&quot;: &quot;Warn&quot;,
        ///	&quot;strErrorTitle&quot;: &quot;Error&quot;,
        ///
        ///	&quot;strGetAllInputStatusSuccess&quot;: &quot;Success to get all input status&quot;,
        ///	&quot;strGetAllInputStatusFailure&quot;: &quot;Failed to get all input status&quot;,
        ///	&quot;strAddDeviceSuccess&quot;: &quot;Success to add device&quot;,
        ///	&quot;strAddDeviceFailure&quot;: &quot;Failed to add device&quot;,
        ///	&quot;strRegisterScreenSaverReques [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string appstring {
            get {
                return ResourceManager.GetString("appstring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Keyboard.
        /// </summary>
        internal static string BindActionValueKeyboard {
            get {
                return ResourceManager.GetString("BindActionValueKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Shutdown.
        /// </summary>
        internal static string BindActionValueShutdown {
            get {
                return ResourceManager.GetString("BindActionValueShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        internal static string BindKeyboardErreur {
            get {
                return ResourceManager.GetString("BindKeyboardErreur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Left button.
        /// </summary>
        internal static string BindMouseValueLeft {
            get {
                return ResourceManager.GetString("BindMouseValueLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Middle button.
        /// </summary>
        internal static string BindMouseValueMiddle {
            get {
                return ResourceManager.GetString("BindMouseValueMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Right button.
        /// </summary>
        internal static string BindMouseValueRight {
            get {
                return ResourceManager.GetString("BindMouseValueRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {
        ///	&quot;appDescriptionLong&quot;: &quot;Servicio que proporciona control remoto de computadora usando un televisor LG WebOS&quot;
        ///}.
        /// </summary>
        internal static string esappinfo {
            get {
                return ResourceManager.GetString("esappinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {
        ///	&quot;strAppTittle&quot;: &quot;MagicRemoteService&quot;,
        ///	&quot;strAppDescriptionLong&quot;: &quot;Servicio que proporciona control remoto de computadora usando un televisor LG WebOS&quot;,
        ///
        ///	&quot;strLogTitle&quot;: &quot;Registro&quot;,
        ///	&quot;strWarnTitle&quot;: &quot;Aviso&quot;,
        ///	&quot;strErrorTitle&quot;: &quot;Error&quot;,
        ///
        ///	&quot;strGetAllInputStatusSuccess&quot;: &quot;Se ha obtenido correctamente el estado de todas las entradas&quot;,
        ///	&quot;strGetAllInputStatusFailure&quot;: &quot;Fallo al obtener el estado de todas las entradas&quot;,
        ///	&quot;strAddDeviceSuccess&quot;: &quot;Se ha añadido el dispositivo correctamente&quot;,
        ///	&quot;strAddDeviceFailure&quot;: &quot; [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string esappstring {
            get {
                return ResourceManager.GetString("esappstring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {
        ///	&quot;appDescriptionLong&quot;: &quot;Service permettant de contrôler un ordinateur à l&apos;aide d&apos;une TV WebOS LG&quot;
        ///}.
        /// </summary>
        internal static string frappinfo {
            get {
                return ResourceManager.GetString("frappinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {
        ///	&quot;strAppTittle&quot;: &quot;MagicRemoteService&quot;,
        ///	&quot;strAppDescriptionLong&quot;: &quot;Service permettant de contrôler un ordinateur à l&apos;aide d&apos;une TV WebOS LG&quot;,
        ///
        ///	&quot;strLogTitle&quot;: &quot;Evenement&quot;,
        ///	&quot;strWarnTitle&quot;: &quot;Attention&quot;,
        ///	&quot;strErrorTitle&quot;: &quot;Erreur&quot;,
        ///
        ///	&quot;strGetAllInputStatusSuccess&quot;: &quot;Succès de la récupération l&apos;état des entrées&quot;,
        ///	&quot;strGetAllInputStatusFailure&quot;: &quot;Echec de la récupération l&apos;état des entrées&quot;,
        ///	&quot;strAddDeviceSuccess&quot;: &quot;Succès de l&apos;ajout de l&apos;appareil&quot;,
        ///	&quot;strAddDeviceFailure&quot;: &quot;Echec de l&apos;ajout de l&apos;appa [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string frappstring {
            get {
                return ResourceManager.GetString("frappstring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///	
        ///&lt;head&gt;
        ///	&lt;title&gt;MagicRemoteService&lt;/title&gt;
        ///	&lt;style type=&quot;text/css&quot;&gt;
        ///		@font-face {
        ///			font-family: Sandstone;
        ///			src: url(&quot;MuseoSans-Medium.ttf&quot;);
        ///		}
        ///		* {
        ///			font-family: Sandstone;
        ///			text-overflow: ellipsis;
        ///		}
        ///
        ///		body {
        ///			margin:0;
        ///			padding:0;
        ///		}
        ///
        ///		.screen {
        ///			position: fixed;
        ///			pointer-events: none;
        ///			
        ///			height: 100%;
        ///			width: 100%;
        ///		}
        ///
        ///		div.flex {
        ///			display: -webkit-flex;
        ///			display: flex;
        ///			-webkit-flex-flow: row wrap;
        ///			flex-fl [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string index {
            get {
                return ResourceManager.GetString("index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} is not a valid entry. Please specify a value between 1 and 255..
        /// </summary>
        internal static string IPAddressBoxErrorByteEntryMessage {
            get {
                return ResourceManager.GetString("IPAddressBoxErrorByteEntryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid entry.
        /// </summary>
        internal static string IPAddressBoxErrorByteEntryTitle {
            get {
                return ResourceManager.GetString("IPAddressBoxErrorByteEntryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You are trying to copy an incorrectly formatted IP address into this field..
        /// </summary>
        internal static string IPAddressBoxErrorPasteMessage {
            get {
                return ResourceManager.GetString("IPAddressBoxErrorPasteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Badly formatted IP address.
        /// </summary>
        internal static string IPAddressBoxErrorPasteTitle {
            get {
                return ResourceManager.GetString("IPAddressBoxErrorPasteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] largeIcon {
            get {
                object obj = ResourceManager.GetObject("largeIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        /// </summary>
        internal static System.Drawing.Icon MagicRemoteService {
            get {
                object obj = ResourceManager.GetObject("MagicRemoteService", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 
        ///ArrayBuffer.prototype.toString = function(base) {
        ///	return Array.prototype.slice.call(new Uint8Array(this)).map(function(x) {
        ///		return (&quot;00&quot; + x.toString(base)).slice(-2);
        ///	}).join(&quot;&quot;);
        ///};
        ///
        ///Window.prototype.oneEventListener = function(strType, fListener) {
        ///	function Handler(inEvent) {
        ///		this.removeEventListener(strType, Handler);
        ///			if(fListener(inEvent) === false) {
        ///			this.addEventListener(strType, Handler);
        ///		}
        ///	}
        ///	this.addEventListener(strType, Handler);
        ///};
        ///Element.prototype.oneEventList [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string main {
            get {
                return ResourceManager.GetString("main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] miniIcon {
            get {
                object obj = ResourceManager.GetObject("miniIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] MuseoSans_Medium {
            get {
                object obj = ResourceManager.GetObject("MuseoSans_Medium", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {
        ///	&quot;name&quot;: &quot;com.cathwyler.magicremoteservice.service&quot;,
        ///	&quot;main&quot;: &quot;service.js&quot;
        ///}.
        /// </summary>
        internal static string package {
            get {
                return ResourceManager.GetString("package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} is not a valid entry. Please specify a value between 0x00 and 0xFF..
        /// </summary>
        internal static string PhysicalAddressBoxErrorByteEntryMessage {
            get {
                return ResourceManager.GetString("PhysicalAddressBoxErrorByteEntryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid entry.
        /// </summary>
        internal static string PhysicalAddressBoxErrorByteEntryTitle {
            get {
                return ResourceManager.GetString("PhysicalAddressBoxErrorByteEntryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You are trying to copy an incorrectly formatted physical address into this field..
        /// </summary>
        internal static string PhysicalAddressBoxErrorPasteMessage {
            get {
                return ResourceManager.GetString("PhysicalAddressBoxErrorPasteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Badly formatted physical address.
        /// </summary>
        internal static string PhysicalAddressBoxErrorPasteTitle {
            get {
                return ResourceManager.GetString("PhysicalAddressBoxErrorPasteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Screen.
        /// </summary>
        internal static string Screen {
            get {
                return ResourceManager.GetString("Screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Default primary screen.
        /// </summary>
        internal static string ScreenPrimaryDefaultUserFriendlyName {
            get {
                return ResourceManager.GetString("ScreenPrimaryDefaultUserFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 
        ///var Service = require(&quot;webos-service&quot;);
        ///var Dgram = require(&quot;dgram&quot;);
        ///
        ///var bDebug = false;
        ///var bOverlay = true;
        ///var strAppId = &quot;com.cathwyler.magicremoteservice&quot;;
        ///
        ///var serService = new Service(strAppId + &quot;.service&quot;); 
        ///
        ///var arrLog = [];
        ///var dLog = {};
        ///var metLog = serService.register(&quot;log&quot;);
        ///metLog.on(&quot;request&quot;, function(mMessage) {
        ///	try {
        ///		if (mMessage.isSubscription) {
        ///			dLog[mMessage.uniqueToken] = mMessage;
        ///			mMessage.respond({
        ///				subscribed: true,
        ///				returnValue: true
        ///			});
        ///	 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string service {
            get {
                return ResourceManager.GetString("service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {
        ///	&quot;id&quot;: &quot;com.cathwyler.magicremoteservice.service&quot;,
        ///	&quot;services&quot;: [
        ///		{
        ///			&quot;name&quot;: &quot;com.cathwyler.magicremoteservice.service&quot;
        ///		}
        ///	]
        ///}.
        /// </summary>
        internal static string services {
            get {
                return ResourceManager.GetString("services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please select a display..
        /// </summary>
        internal static string SettingDisplaySelectErrorMessage {
            get {
                return ResourceManager.GetString("SettingDisplaySelectErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The display has not been selected.
        /// </summary>
        internal static string SettingDisplaySelectErrorTitle {
            get {
                return ResourceManager.GetString("SettingDisplaySelectErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error refreshing TV inputs.
        /// </summary>
        internal static string SettingInputRefreshlErrorTitle {
            get {
                return ResourceManager.GetString("SettingInputRefreshlErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please select a TV input..
        /// </summary>
        internal static string SettingInputSelectErrorMessage {
            get {
                return ResourceManager.GetString("SettingInputSelectErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The TV input has not been selected.
        /// </summary>
        internal static string SettingInputSelectErrorTitle {
            get {
                return ResourceManager.GetString("SettingInputSelectErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} is not a valid physical address. Please specify a valid physical address..
        /// </summary>
        internal static string SettingPCMacErrorMessage {
            get {
                return ResourceManager.GetString("SettingPCMacErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid physical address.
        /// </summary>
        internal static string SettingPCMacErrorTitle {
            get {
                return ResourceManager.GetString("SettingPCMacErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while saving PC configuration.
        /// </summary>
        internal static string SettingPCSaveErrorTittle {
            get {
                return ResourceManager.GetString("SettingPCSaveErrorTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to save the changes made to the PC service ?.
        /// </summary>
        internal static string SettingPCSaveMessage {
            get {
                return ResourceManager.GetString("SettingPCSaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while saving remote configuration.
        /// </summary>
        internal static string SettingRemoteSaveErrorTittle {
            get {
                return ResourceManager.GetString("SettingRemoteSaveErrorTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to save the changes made to the remote keybind ?.
        /// </summary>
        internal static string SettingRemoteSaveMessage {
            get {
                return ResourceManager.GetString("SettingRemoteSaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} is not a valid IP address. Please specify a valid IP address..
        /// </summary>
        internal static string SettingSendIPErrorMessage {
            get {
                return ResourceManager.GetString("SettingSendIPErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid IP address.
        /// </summary>
        internal static string SettingSendIPErrorTitle {
            get {
                return ResourceManager.GetString("SettingSendIPErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} is not a valid subnet mask. Please specify a valid subnet mask..
        /// </summary>
        internal static string SettingSubnetMaskErrorMessage {
            get {
                return ResourceManager.GetString("SettingSubnetMaskErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid subnet mask.
        /// </summary>
        internal static string SettingSubnetMaskErrorTitle {
            get {
                return ResourceManager.GetString("SettingSubnetMaskErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while adding TV.
        /// </summary>
        internal static string SettingTVAddErrorTitle {
            get {
                return ResourceManager.GetString("SettingTVAddErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while inspecting running application on TV.
        /// </summary>
        internal static string SettingTVInspectErrorTittle {
            get {
                return ResourceManager.GetString("SettingTVInspectErrorTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while installing application on TV.
        /// </summary>
        internal static string SettingTVInstallErrorTitle {
            get {
                return ResourceManager.GetString("SettingTVInstallErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while modifying TV.
        /// </summary>
        internal static string SettingTVModifyErrorTitle {
            get {
                return ResourceManager.GetString("SettingTVModifyErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while refreshing TVs.
        /// </summary>
        internal static string SettingTVRefreshlErrorTitle {
            get {
                return ResourceManager.GetString("SettingTVRefreshlErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while removing TV.
        /// </summary>
        internal static string SettingTVRemoveErrorTitle {
            get {
                return ResourceManager.GetString("SettingTVRemoveErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to install the changes made to the TV app ?.
        /// </summary>
        internal static string SettingTVSaveMessage {
            get {
                return ResourceManager.GetString("SettingTVSaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please select a TV.
        /// </summary>
        internal static string SettingTVSelectErrorMessage {
            get {
                return ResourceManager.GetString("SettingTVSelectErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The TV has not been selected.
        /// </summary>
        internal static string SettingTVSelectErrorTitle {
            get {
                return ResourceManager.GetString("SettingTVSelectErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while retrieving TV version.
        /// </summary>
        internal static string SettingTVVersionErrorTitle {
            get {
                return ResourceManager.GetString("SettingTVVersionErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à window.webOS=function(e){var t={};function n(o){if(t[o])return t[o].exports;var r=t[o]={i:o,l:!1,exports:{}};return e[o].call(r.exports,r,r.exports,n),r.l=!0,r.exports}return n.m=e,n.c=t,n.d=function(e,t,o){n.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:o})},n.r=function(e){&quot;undefined&quot;!=typeof Symbol&amp;&amp;Symbol.toStringTag&amp;&amp;Object.defineProperty(e,Symbol.toStringTag,{value:&quot;Module&quot;}),Object.defineProperty(e,&quot;__esModule&quot;,{value:!0})},n.t=function(e,t){if(1&amp;t&amp;&amp;(e=n(e)),8&amp;t)return e;if(4&amp;t&amp;&amp;&quot;object&quot;==type [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string webOSTV {
            get {
                return ResourceManager.GetString("webOSTV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à window.webOSDev=function(e){var r={};function t(n){if(r[n])return r[n].exports;var o=r[n]={i:n,l:!1,exports:{}};return e[n].call(o.exports,o,o.exports,t),o.l=!0,o.exports}return t.m=e,t.c=r,t.d=function(e,r,n){t.o(e,r)||Object.defineProperty(e,r,{enumerable:!0,get:n})},t.r=function(e){&quot;undefined&quot;!=typeof Symbol&amp;&amp;Symbol.toStringTag&amp;&amp;Object.defineProperty(e,Symbol.toStringTag,{value:&quot;Module&quot;}),Object.defineProperty(e,&quot;__esModule&quot;,{value:!0})},t.t=function(e,r){if(1&amp;r&amp;&amp;(e=t(e)),8&amp;r)return e;if(4&amp;r&amp;&amp;&quot;object&quot;==t [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string webOSTV_dev {
            get {
                return ResourceManager.GetString("webOSTV_dev", resourceCulture);
            }
        }
    }
}
